import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const educationSidebars: SidebarsConfig = {
  educationSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default educationSidebars;
