import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const learnSidebars: SidebarsConfig = {
  learnSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default learnSidebars;
