import Link from '@docusaurus/Link';
import { translate } from '@docusaurus/Translate';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import DocsLink from '@site/src/components/DocsLink';
import Layout from '@theme/Layout';
import { JSX } from 'react';
import styles from './index.module.css';

const GITHUB_URL = 'https://github.com/dartway/dartway';

/**
 * Every string on this page goes through `translate()` so that
 * `npm run write-translations` can extract it. The Russian side lives in
 * i18n/ru/code.json and is generated by `npm run translate` — never edited by
 * hand, same rule as everything else under i18n/ru. See CLAUDE.md.
 *
 * Product names, platform names and metrics are deliberately left as literals:
 * they are the same in both languages, and a translation key for "iOS" is a
 * key that can only ever be got wrong.
 *
 * A function rather than a module-level constant so the lookup happens when the
 * page renders, not when the module is first imported.
 */
function pageContent() {
  return {
    title: 'DartWay',
    description: translate({
      id: 'landing.meta.description',
      description: 'The meta description of the landing page',
      message:
        'DartWay is a full-stack Flutter + Serverpod framework for shipping real products faster with stricter architecture and less boilerplate.',
    }),
    heroTitle: translate({
      id: 'landing.hero.title',
      description: 'Landing hero headline',
      message: 'Apps in days, not months',
    }),
    heroKicker: translate({
      id: 'landing.hero.kicker',
      description: 'Line under the hero headline naming the audience',
      message: 'for Flutter + Serverpod teams',
    }),
    heroSubtitle: translate({
      id: 'landing.hero.subtitle',
      description: 'Landing hero supporting paragraph',
      message:
        'Strict architecture, generated structure, and ready product primitives so teams can build with less boilerplate and fewer architectural mistakes.',
    }),
    heroMeta: [
      translate({
        id: 'landing.hero.meta.speed',
        description: 'Hero fact: delivery speed',
        message: '3-5x faster delivery',
      }),
      translate({
        id: 'landing.hero.meta.products',
        description: 'Hero fact: how many products shipped',
        message: '10+ shipped products',
      }),
      'Flutter + Serverpod',
    ],
    primaryCta: translate({
      id: 'landing.cta.docs',
      description: 'Primary hero button, leads to the documentation',
      message: 'Open documentation',
    }),
    secondaryCta: 'GitHub',
    stats: [
      [
        translate({
          id: 'landing.stats.architecture.title',
          description: 'Hero stat card title',
          message: 'Strict architecture',
        }),
        translate({
          id: 'landing.stats.architecture.text',
          description: 'Hero stat card body',
          message: 'UI, local logic, domain logic, and shared components stay separated by default.',
        }),
      ],
      [
        translate({
          id: 'landing.stats.core.title',
          description: 'Hero stat card title',
          message: 'Typed product core',
        }),
        translate({
          id: 'landing.stats.core.text',
          description: 'Hero stat card body',
          message: 'Models, CRUD rules, filters, and data flows stay explicit across frontend and backend.',
        }),
      ],
      [
        translate({
          id: 'landing.stats.ai.title',
          description: 'Hero stat card title',
          message: 'AI-friendly codebase',
        }),
        translate({
          id: 'landing.stats.ai.text',
          description: 'Hero stat card body',
          message: 'Consistent patterns make generation, review, and scaling much more predictable.',
        }),
      ],
    ],
    casesTitle: translate({
      id: 'landing.cases.title',
      description: 'Heading of the case studies section',
      message: 'Products built with DartWay',
    }),
    casesFooter: translate({
      id: 'landing.cases.footer',
      description: 'Line closing the case studies section',
      message:
        'And dozens of other shipped flows, internal tools, and startup releases built on the same foundation.',
    }),
    cases: [
      {
        title: 'TVAITY',
        subtitle: translate({
          id: 'landing.cases.tvaity.subtitle',
          description: 'One-line description of the TVAITY case',
          message: 'Financial literacy app with regular content and chats',
        }),
        logo: '/img/tvaity_icon.png',
        status: translate({
          id: 'landing.cases.tvaity.status',
          description: 'Category label on the TVAITY case card',
          message: 'EdTech platform',
        }),
        platforms: ['Android', 'iOS', 'Web'],
        facts: [
          translate({ id: 'landing.cases.fact.chats', description: 'Case feature chip', message: 'Chats' }),
          translate({ id: 'landing.cases.fact.lms', description: 'Case feature chip', message: 'LMS' }),
          translate({ id: 'landing.cases.fact.analytics', description: 'Case feature chip', message: 'Analytics' }),
          translate({ id: 'landing.cases.fact.admin', description: 'Case feature chip', message: 'Admin panel' }),
        ],
        metric: '> 700 DAU',
        result: translate({
          id: 'landing.cases.tvaity.result',
          description: 'What the TVAITY project achieved',
          message:
            'Helped an online school move work from Telegram and LMS into its own application and create a unique learning experience for students.',
        }),
      },
      {
        title: 'Kerla',
        subtitle: translate({
          id: 'landing.cases.kerla.subtitle',
          description: 'One-line description of the Kerla case',
          message: 'Region-specific classified with social elements',
        }),
        logo: '/img/kerla_icon.webp',
        status: translate({
          id: 'landing.cases.kerla.status',
          description: 'Category label on the Kerla case card',
          message: 'E-commerce startup',
        }),
        platforms: ['Android', 'iOS'],
        facts: [
          translate({ id: 'landing.cases.fact.listings', description: 'Case feature chip', message: 'Listings' }),
          translate({ id: 'landing.cases.fact.chats2', description: 'Case feature chip', message: 'Chats' }),
          translate({ id: 'landing.cases.fact.stories', description: 'Case feature chip', message: 'Stories' }),
          translate({ id: 'landing.cases.fact.payments', description: 'Case feature chip', message: 'Payments' }),
        ],
        metric: translate({
          id: 'landing.cases.kerla.metric',
          description: 'Headline number on the Kerla case card',
          message: '> 5000 Users',
        }),
        result: translate({
          id: 'landing.cases.kerla.result',
          description: 'What the Kerla project achieved',
          message:
            'Helped the founder turn ideas into product, launch on a local market, and keep expanding the feature set.',
        }),
      },
    ],
    servicesTitle: translate({
      id: 'landing.services.title',
      description: 'Heading of the features section',
      message: 'What the framework gives you',
    }),
    services: [
      [
        translate({
          id: 'landing.services.structure.title',
          description: 'Feature card title',
          message: 'Feature-first structure',
        }),
        translate({
          id: 'landing.services.structure.text',
          description: 'Feature card body',
          message:
            'A predictable application layout for features, shared UI, local state, and domain logic.',
        }),
      ],
      [
        translate({
          id: 'landing.services.pipeline.title',
          description: 'Feature card title',
          message: 'Unified data pipeline',
        }),
        translate({
          id: 'landing.services.pipeline.text',
          description: 'Feature card body',
          message:
            'Backend models, API, validation, filters, persistence, and UI lists follow one model-driven flow.',
        }),
      ],
      [
        translate({
          id: 'landing.services.primitives.title',
          description: 'Feature card title',
          message: 'Ready product primitives',
        }),
        translate({
          id: 'landing.services.primitives.text',
          description: 'Feature card body',
          message:
            'Auth, roles, admin flows, CRUD configs, loading states, errors, and real-time updates are built in.',
        }),
      ],
      [
        translate({
          id: 'landing.services.crossplatform.title',
          description: 'Feature card title',
          message: 'Cross-platform delivery',
        }),
        translate({
          id: 'landing.services.crossplatform.text',
          description: 'Feature card body',
          message:
            'One Dart stack for iOS, Android, Web, and operational panels without fragmented architecture.',
        }),
      ],
    ],
    proofTitle: translate({
      id: 'landing.proof.title',
      description: 'Heading of the reasons-to-switch section',
      message: 'Why teams switch to DartWay',
    }),
    proof: [
      translate({
        id: 'landing.proof.glue',
        description: 'Reason to switch',
        message: 'It removes repeated glue code between models, backend rules, state, and UI.',
      }),
      translate({
        id: 'landing.proof.patterns',
        description: 'Reason to switch',
        message:
          'It fixes core patterns early, so products do not drift into inconsistent architecture later.',
      }),
      translate({
        id: 'landing.proof.ai',
        description: 'Reason to switch',
        message:
          'It gives AI and engineers the same boundaries, which makes code generation and review safer.',
      }),
      translate({
        id: 'landing.proof.production',
        description: 'Reason to switch',
        message: 'It is already validated in production products, not just demo repositories.',
      }),
    ],
    processTitle: translate({
      id: 'landing.process.title',
      description: 'Heading of the adoption steps section',
      message: 'How teams adopt it',
    }),
    process: [
      [
        translate({ id: 'landing.process.scaffold.title', description: 'Adoption step name', message: 'Scaffold' }),
        translate({
          id: 'landing.process.scaffold.text',
          description: 'Adoption step body',
          message: 'Start from a full-stack DartWay base instead of assembling architecture from scratch.',
        }),
      ],
      [
        translate({ id: 'landing.process.define.title', description: 'Adoption step name', message: 'Define' }),
        translate({
          id: 'landing.process.define.text',
          description: 'Adoption step body',
          message:
            'Describe models and rules once, then keep frontend and backend aligned through the same system.',
        }),
      ],
      [
        translate({ id: 'landing.process.build.title', description: 'Adoption step name', message: 'Build' }),
        translate({
          id: 'landing.process.build.text',
          description: 'Adoption step body',
          message:
            'Ship features through shared patterns, typed APIs, reactive views, and reusable product modules.',
        }),
      ],
      [
        translate({ id: 'landing.process.scale.title', description: 'Adoption step name', message: 'Scale' }),
        translate({
          id: 'landing.process.scale.text',
          description: 'Adoption step body',
          message: 'Grow the product without rewriting the foundation every time the scope expands.',
        }),
      ],
    ],
    finalTitle: translate({
      id: 'landing.final.title',
      description: 'Heading of the closing call to action',
      message: 'Want to evaluate DartWay for your next product?',
    }),
    finalText: translate({
      id: 'landing.final.text',
      description: 'Body of the closing call to action',
      message:
        'Start with the docs, inspect the architecture, and reach out if you want to discuss adoption or a real product use case.',
    }),
    contactCta: translate({
      id: 'landing.cta.telegram',
      description: 'Closing button, leads to the Telegram community',
      message: 'Join Telegram',
    }),
  };
}

export default function Home(): JSX.Element {
  const t = pageContent();

  // Each locale has its own Telegram channel, so this is not a translated
  // string but a different destination — see TELEGRAM_URL in the config, which
  // is also what the footer link uses.
  const { siteConfig } = useDocusaurusContext();
  const telegramUrl = siteConfig.customFields?.telegramUrl as string;

  return (
    <Layout title={t.title} description={t.description} wrapperClassName="homePage">
      <main className={styles.main}>
        <section className={styles.hero}>
          <p className={styles.eyebrow}>DartWay Framework</p>
          <h1 className={styles.heroTitle}>{t.heroTitle}</h1>
          <p className={styles.heroKicker}>{t.heroKicker}</p>
          <p className={styles.heroSubtitle}>{t.heroSubtitle}</p>
          <div className={styles.heroButtons}>
            <DocsLink className="button button--primary button--lg" data-cta="hero-docs">
              {t.primaryCta}
            </DocsLink>
            <Link className={styles.secondaryCta} to={GITHUB_URL} data-cta="hero-github">
              {t.secondaryCta}
            </Link>
          </div>
          <div className={styles.heroMeta}>
            {t.heroMeta.map((item) => (
              <span key={item}>{item}</span>
            ))}
          </div>
          <div className={styles.statsGrid}>
            {t.stats.map(([value, label]) => (
              <div className={styles.statItem} key={value}>
                <strong>{value}</strong>
                <span>{label}</span>
              </div>
            ))}
          </div>
        </section>

        <section className={styles.featuresSection}>
          <h2>{t.casesTitle}</h2>
          <div className={styles.caseGrid}>
            {t.cases.map((caseItem) => (
              <article className={styles.caseCard} key={caseItem.title}>
                <div className={styles.caseHeader}>
                  <div className={styles.caseLogo}>
                    <img src={caseItem.logo} alt={`${caseItem.title} logo`} />
                  </div>
                  <div>
                    <span className={styles.caseStatus}>{caseItem.status}</span>
                    <h3>{caseItem.title}</h3>
                    <p>{caseItem.subtitle}</p>
                  </div>
                  <div className={styles.caseMetric}>{caseItem.metric}</div>
                </div>
                <div className={styles.caseChips}>
                  {caseItem.platforms.map((platform) => (
                    <span key={platform}>{platform}</span>
                  ))}
                </div>
                <ul className={styles.caseFacts}>
                  {caseItem.facts.map((fact) => (
                    <li key={fact}>{fact}</li>
                  ))}
                </ul>
                <p className={styles.caseResult}>{caseItem.result}</p>
              </article>
            ))}
          </div>
          <p className={styles.casesFooter}>{t.casesFooter}</p>
        </section>

        <section className={styles.featuresSection}>
          <h2>{t.servicesTitle}</h2>
          <div className={styles.featuresGrid}>
            {t.services.map(([title, text]) => (
              <article className={styles.featureCard} key={title}>
                <h3>{title}</h3>
                <p>{text}</p>
              </article>
            ))}
          </div>
        </section>

        <section className={styles.section}>
          <h2>{t.proofTitle}</h2>
          <ul className={styles.checkList}>
            {t.proof.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </section>

        <section className={styles.featuresSection}>
          <h2>{t.processTitle}</h2>
          <div className={styles.featuresGrid}>
            {t.process.map(([title, text]) => (
              <article className={styles.featureCard} key={title}>
                <span className={styles.emoji}>{title}</span>
                <p>{text}</p>
              </article>
            ))}
          </div>
        </section>

        <section className={styles.ctaSection}>
          <h2>{t.finalTitle}</h2>
          <p>{t.finalText}</p>
          <Link className="button button--primary button--lg" to={telegramUrl} data-cta="footer-telegram">
            {t.contactCta}
          </Link>
        </section>
      </main>
    </Layout>
  );
}
