import Link from '@docusaurus/Link';
import { translate } from '@docusaurus/Translate';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import DocsLink from '@site/src/components/DocsLink';
import Layout from '@theme/Layout';
import { JSX } from 'react';
import styles from './index.module.css';

const GITHUB_URL = 'https://github.com/dartway/dartway';

/**
 * Every string on this page goes through `translate()` so that
 * `npm run write-translations` can extract it. The Russian side lives in
 * i18n/ru/code.json and is generated by `npm run translate` — never edited by
 * hand, same rule as everything else under i18n/ru. See CLAUDE.md.
 *
 * Product names, platform names and metrics are deliberately left as literals:
 * they are the same in both languages, and a translation key for "iOS" is a
 * key that can only ever be got wrong.
 *
 * A function rather than a module-level constant so the lookup happens when the
 * page renders, not when the module is first imported.
 */
function pageContent() {
  return {
    title: 'DartWay',
    description: translate({
      id: 'landing.meta.description.v2',
      description: 'The meta description of the landing page',
      message:
        'DartWay is an open-source fullstack Dart framework: a Dart server, a Flutter app and one shared contract between them, built to be developed with AI coding agents.',
    }),
    heroTitle: translate({
      id: 'landing.hero.title',
      description: 'Landing hero headline',
      message: 'Apps in days, not months',
    }),
    heroKicker: translate({
      id: 'landing.hero.kicker.v2',
      description: 'Line under the hero headline: what the framework is',
      message: 'Fullstack Dart, built for AI coding agents',
    }),
    heroSubtitle: translate({
      id: 'landing.hero.subtitle.v2',
      description: 'Landing hero supporting paragraph',
      message:
        'A Dart server, a Flutter app and one shared contract between them. Your agent writes features into a structure it cannot bend; you review architecture, not glue code.',
    }),
    heroMeta: [
      translate({
        id: 'landing.hero.meta.products',
        description: 'Hero fact: how many products shipped',
        message: '10+ shipped products',
      }),
      'Dart server + Flutter',
      'Open source · Apache 2.0',
    ],
    primaryCta: translate({
      id: 'landing.cta.docs',
      description: 'Primary hero button, leads to the documentation',
      message: 'Open documentation',
    }),
    secondaryCta: 'GitHub',
    stats: [
      [
        translate({
          id: 'landing.stats.agent.title',
          description: 'Hero stat card title',
          message: 'Start with an agent',
        }),
        translate({
          id: 'landing.stats.agent.text',
          description: 'Hero stat card body',
          message:
            'Open an empty folder in Claude Code, Cursor or Codex and ask it to run dartway quickstart. The agent gets the whole setup instruction and brings the project up.',
        }),
      ],
      [
        translate({
          id: 'landing.stats.contract.title',
          description: 'Hero stat card title',
          message: 'One contract',
        }),
        translate({
          id: 'landing.stats.contract.text',
          description: 'Hero stat card body',
          message:
            'Every call, every object and every refusal is a class in a package both sides compile. Nothing else crosses the wire.',
        }),
      ],
      [
        translate({
          id: 'landing.stats.live.title',
          description: 'Hero stat card title',
          message: 'Live by default',
        }),
        translate({
          id: 'landing.stats.live.text',
          description: 'Hero stat card body',
          message:
            'A list open on one screen updates when the data changes on the server: no reload, no cache written by hand.',
        }),
      ],
    ],
    casesTitle: translate({
      id: 'landing.cases.title',
      description: 'Heading of the case studies section',
      message: 'Products built with DartWay',
    }),
    casesFooter: translate({
      id: 'landing.cases.footer',
      description: 'Line closing the case studies section',
      message:
        'And dozens of other shipped flows, internal tools, and startup releases built on the same foundation.',
    }),
    cases: [
      {
        title: 'TVAITY',
        subtitle: translate({
          id: 'landing.cases.tvaity.subtitle',
          description: 'One-line description of the TVAITY case',
          message: 'Financial literacy app with regular content and chats',
        }),
        logo: '/img/tvaity_icon.png',
        status: translate({
          id: 'landing.cases.tvaity.status',
          description: 'Category label on the TVAITY case card',
          message: 'EdTech platform',
        }),
        platforms: ['Android', 'iOS', 'Web'],
        facts: [
          translate({ id: 'landing.cases.fact.chats', description: 'Case feature chip', message: 'Chats' }),
          translate({ id: 'landing.cases.fact.lms', description: 'Case feature chip', message: 'LMS' }),
          translate({ id: 'landing.cases.fact.analytics', description: 'Case feature chip', message: 'Analytics' }),
          translate({ id: 'landing.cases.fact.admin', description: 'Case feature chip', message: 'Admin panel' }),
        ],
        metric: '> 700 DAU',
        result: translate({
          id: 'landing.cases.tvaity.result',
          description: 'What the TVAITY project achieved',
          message:
            'Helped an online school move work from Telegram and LMS into its own application and create a unique learning experience for students.',
        }),
      },
      {
        title: 'Kerla',
        subtitle: translate({
          id: 'landing.cases.kerla.subtitle',
          description: 'One-line description of the Kerla case',
          message: 'Region-specific classified with social elements',
        }),
        logo: '/img/kerla_icon.webp',
        status: translate({
          id: 'landing.cases.kerla.status',
          description: 'Category label on the Kerla case card',
          message: 'E-commerce startup',
        }),
        platforms: ['Android', 'iOS'],
        facts: [
          translate({ id: 'landing.cases.fact.listings', description: 'Case feature chip', message: 'Listings' }),
          translate({ id: 'landing.cases.fact.chats2', description: 'Case feature chip', message: 'Chats' }),
          translate({ id: 'landing.cases.fact.stories', description: 'Case feature chip', message: 'Stories' }),
          translate({ id: 'landing.cases.fact.payments', description: 'Case feature chip', message: 'Payments' }),
        ],
        metric: translate({
          id: 'landing.cases.kerla.metric',
          description: 'Headline number on the Kerla case card',
          message: '> 5000 Users',
        }),
        result: translate({
          id: 'landing.cases.kerla.result',
          description: 'What the Kerla project achieved',
          message:
            'Helped the founder turn ideas into product, launch on a local market, and keep expanding the feature set.',
        }),
      },
    ],
    servicesTitle: translate({
      id: 'landing.services.title',
      description: 'Heading of the features section',
      message: 'What the framework gives you',
    }),
    services: [
      [
        translate({
          id: 'landing.services.endpoints.title',
          description: 'Feature card title',
          message: 'No endpoints to write',
        }),
        translate({
          id: 'landing.services.endpoints.text',
          description: 'Feature card body',
          message:
            'Declare a request or a command in the contract, write one handler on the server, watch it in a widget. No route, client method or cache in between.',
        }),
      ],
      [
        translate({
          id: 'landing.services.commands.title',
          description: 'Feature card title',
          message: 'Safe retries, readable refusals',
        }),
        translate({
          id: 'landing.services.commands.text',
          description: 'Feature card body',
          message:
            'A retried command runs once. A refusal comes back as a code and is shown in the user’s language.',
        }),
      ],
      [
        translate({
          id: 'landing.services.primitives.v2.title',
          description: 'Feature card title',
          message: 'Product basics included',
        }),
        translate({
          id: 'landing.services.primitives.v2.text',
          description: 'Feature card body',
          message:
            'Sign-in, profiles, roles, an admin panel, a UI kit, push, uploads and background jobs come with the generated project.',
        }),
      ],
      [
        translate({
          id: 'landing.services.cli.title',
          description: 'Feature card title',
          message: 'From create to deploy',
        }),
        translate({
          id: 'landing.services.cli.text',
          description: 'Feature card body',
          message:
            'dartway create, check and deploy: one CLI for the whole life of a project, and a checker that catches what the analyzer cannot see.',
        }),
      ],
    ],
    proofTitle: translate({
      id: 'landing.proof.title.v2',
      description: 'Heading of the reasons-to-use section',
      message: 'Why developers use DartWay',
    }),
    proof: [
      translate({
        id: 'landing.proof.glue.v2',
        description: 'Reason to use',
        message:
          'No glue between server and app: the contract is the API, the client and the types at once.',
      }),
      translate({
        id: 'landing.proof.agents',
        description: 'Reason to use',
        message:
          'Agents get the same strict boundaries as engineers, so generated code lands in the right place and review stays about architecture.',
      }),
      translate({
        id: 'landing.proof.checker',
        description: 'Reason to use',
        message:
          'Conventions are checked by a tool, not by memory: dartway check reads the whole project and fails when a feature leaves the pattern.',
      }),
      translate({
        id: 'landing.proof.production',
        description: 'Reason to use',
        message:
          'It is already validated in production products, not just demo repositories.',
      }),
    ],
    processTitle: translate({
      id: 'landing.process.title.v2',
      description: 'Heading of the getting-started steps section',
      message: 'How to start',
    }),
    process: [
      [
        translate({ id: 'landing.process.install.title', description: 'Getting-started step name', message: 'Install' }),
        translate({
          id: 'landing.process.install.text',
          description: 'Getting-started step body',
          message: 'dart pub global activate dartway_cli: the only thing to put on the machine by hand.',
        }),
      ],
      [
        translate({ id: 'landing.process.ask.title', description: 'Getting-started step name', message: 'Ask your agent' }),
        translate({
          id: 'landing.process.ask.text',
          description: 'Getting-started step body',
          message: 'dartway quickstart prints the setup instruction into any agent. Say what you want: set up my_app and bring it up.',
        }),
      ],
      [
        translate({ id: 'landing.process.contract.title', description: 'Getting-started step name', message: 'Describe the contract' }),
        translate({
          id: 'landing.process.contract.text',
          description: 'Getting-started step body',
          message: 'A feature starts as a few classes in the shared package. The server handles them, the app watches them.',
        }),
      ],
      [
        translate({ id: 'landing.process.deploy.title', description: 'Getting-started step name', message: 'Deploy' }),
        translate({
          id: 'landing.process.deploy.text',
          description: 'Getting-started step body',
          message: 'dartway deploy takes the project to your own Linux server with Docker. The same CLI updates the project when the framework moves on.',
        }),
      ],
    ],
    finalTitle: translate({
      id: 'landing.final.title.v2',
      description: 'Heading of the closing call to action',
      message: 'Try it on your next project',
    }),
    finalText: translate({
      id: 'landing.final.text.v2',
      description: 'Body of the closing call to action',
      message:
        'Read the docs or hand the quickstart to your agent. Releases, new episodes and questions live in our Telegram channel.',
    }),
    contactCta: translate({
      id: 'landing.cta.telegram',
      description: 'Closing button, leads to the Telegram community',
      message: 'Join Telegram',
    }),
  };
}

export default function Home(): JSX.Element {
  const t = pageContent();

  // Each locale has its own Telegram channel, so this is not a translated
  // string but a different destination — see TELEGRAM_URL in the config, which
  // is also what the footer link uses.
  const { siteConfig } = useDocusaurusContext();
  const telegramUrl = siteConfig.customFields?.telegramUrl as string;

  return (
    <Layout title={t.title} description={t.description} wrapperClassName="homePage">
      <main className={styles.main}>
        <section className={styles.hero}>
          <p className={styles.eyebrow}>DartWay Framework</p>
          <h1 className={styles.heroTitle}>{t.heroTitle}</h1>
          <p className={styles.heroKicker}>{t.heroKicker}</p>
          <p className={styles.heroSubtitle}>{t.heroSubtitle}</p>
          <div className={styles.heroButtons}>
            <DocsLink className="button button--primary button--lg" data-cta="hero-docs">
              {t.primaryCta}
            </DocsLink>
            <Link className={styles.secondaryCta} to={GITHUB_URL} data-cta="hero-github">
              {t.secondaryCta}
            </Link>
          </div>
          <div className={styles.heroMeta}>
            {t.heroMeta.map((item) => (
              <span key={item}>{item}</span>
            ))}
          </div>
          <div className={styles.statsGrid}>
            {t.stats.map(([value, label]) => (
              <div className={styles.statItem} key={value}>
                <strong>{value}</strong>
                <span>{label}</span>
              </div>
            ))}
          </div>
        </section>

        <section className={styles.featuresSection}>
          <h2>{t.casesTitle}</h2>
          <div className={styles.caseGrid}>
            {t.cases.map((caseItem) => (
              <article className={styles.caseCard} key={caseItem.title}>
                <div className={styles.caseHeader}>
                  <div className={styles.caseLogo}>
                    <img src={caseItem.logo} alt={`${caseItem.title} logo`} />
                  </div>
                  <div>
                    <span className={styles.caseStatus}>{caseItem.status}</span>
                    <h3>{caseItem.title}</h3>
                    <p>{caseItem.subtitle}</p>
                  </div>
                  <div className={styles.caseMetric}>{caseItem.metric}</div>
                </div>
                <div className={styles.caseChips}>
                  {caseItem.platforms.map((platform) => (
                    <span key={platform}>{platform}</span>
                  ))}
                </div>
                <ul className={styles.caseFacts}>
                  {caseItem.facts.map((fact) => (
                    <li key={fact}>{fact}</li>
                  ))}
                </ul>
                <p className={styles.caseResult}>{caseItem.result}</p>
              </article>
            ))}
          </div>
          <p className={styles.casesFooter}>{t.casesFooter}</p>
        </section>

        <section className={styles.featuresSection}>
          <h2>{t.servicesTitle}</h2>
          <div className={styles.featuresGrid}>
            {t.services.map(([title, text]) => (
              <article className={styles.featureCard} key={title}>
                <h3>{title}</h3>
                <p>{text}</p>
              </article>
            ))}
          </div>
        </section>

        <section className={styles.section}>
          <h2>{t.proofTitle}</h2>
          <ul className={styles.checkList}>
            {t.proof.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </section>

        <section className={styles.featuresSection}>
          <h2>{t.processTitle}</h2>
          <div className={styles.featuresGrid}>
            {t.process.map(([title, text]) => (
              <article className={styles.featureCard} key={title}>
                <span className={styles.emoji}>{title}</span>
                <p>{text}</p>
              </article>
            ))}
          </div>
        </section>

        <section className={styles.ctaSection}>
          <h2>{t.finalTitle}</h2>
          <p>{t.finalText}</p>
          <Link className="button button--primary button--lg" to={telegramUrl} data-cta="footer-telegram">
            {t.contactCta}
          </Link>
        </section>
      </main>
    </Layout>
  );
}
