#!/usr/bin/env node
/**
 * Sync framework documentation from the dartway/dartway monorepo into docs/.
 *
 * docs/ in this repository is generated output. The source of truth is docs/ in
 * the monorepo, where a page travels in the same pull request as the code it
 * describes. See STRATEGY.md for why the boundary exists.
 *
 *   npm run sync-docs                 # default branch (see BRANCH)
 *   npm run sync-docs -- --branch stable
 *   npm run sync-docs -- --check      # report drift, write nothing, exit 1 if stale
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = 'https://github.com/dartway/dartway.git';

/**
 * Which branch the published docs describe.
 *
 * `stable` is what `dartway create` actually hands a user and is the correct
 * source in principle. We track `master` while `stable` is not promoted often
 * enough — fresh-but-slightly-ahead beats stale. Flip this line when promotion
 * becomes regular.
 */
const BRANCH = 'master';

/** Path to the docs folder inside the monorepo. */
const SOURCE_DIR = 'docs';

/**
 * Files in the monorepo's docs/ that are internal and must not be published.
 * DESIGN.md is marked as such in the monorepo itself; README.md describes the
 * folder to whoever writes it.
 */
const EXCLUDE = new Set(['README.md', 'DESIGN.md']);

/**
 * Sidebar labels per source folder. The numeric prefix sets the order and is
 * stripped by Docusaurus when building URLs, so `1-getting-started` serves at
 * /docs/getting-started. A folder missing here still syncs — it just gets a
 * label derived from its name, and shows up in the run summary so we notice.
 */
const CATEGORY_LABELS = {
  '1-getting-started': 'Getting Started',
  '2-core': 'Core',
  '3-flutter': 'Flutter',
  '4-server': 'Server',
  '5-tooling': 'Tooling',
  '6-studio': 'Studio',
};

/**
 * Links in the monorepo that point outside docs/ resolve fine in the monorepo
 * and nowhere on the site. Docusaurus builds with onBrokenLinks: 'throw', so an
 * unrewritten one fails the deploy. Each entry maps a link target to its public
 * URL.
 */
const EXTERNAL_LINK_REWRITES = [
  [
    /\]\(\.\.\/packages\/([^)]+?)\/README\.md\)/g,
    `](${REPO.replace(/\.git$/, '')}/blob/${BRANCH}/packages/$1/README.md)`,
  ],
];

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DEST = path.join(ROOT, 'docs');

const GENERATED_NOTICE =
  '<!-- Generated by scripts/sync-docs.mjs from dartway/dartway. Do not edit: the next sync overwrites it. -->';

function main() {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const branchArg = args.indexOf('--branch');
  const branch = branchArg !== -1 ? args[branchArg + 1] : BRANCH;

  if (branchArg !== -1 && !branch) {
    fail('--branch needs a branch name');
  }

  console.log(`Syncing docs from ${REPO} @ ${branch}${check ? ' (check only)' : ''}`);

  const checkout = cloneDocs(branch);
  try {
    const sourceRoot = path.join(checkout, SOURCE_DIR);
    if (!fs.existsSync(sourceRoot)) {
      fail(`${SOURCE_DIR}/ not found in ${REPO} @ ${branch}`);
    }

    const pages = collectPages(sourceRoot);
    if (pages.length === 0) {
      fail(`no markdown pages found under ${SOURCE_DIR}/ — refusing to wipe docs/`);
    }

    const files = buildOutput(sourceRoot, pages);

    if (check) {
      reportDrift(files);
      return;
    }

    writeOutput(files);
    console.log(`\n${pages.length} pages synced into docs/`);
    console.log('Run `npm run build` before pushing — onBrokenLinks is set to throw.');
  } finally {
    fs.rmSync(checkout, { recursive: true, force: true });
  }
}

/** Shallow, blobless, sparse clone of just the docs folder. */
function cloneDocs(branch) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'dartway-docs-'));
  try {
    git(['clone', '--depth', '1', '--branch', branch, '--filter=blob:none', '--sparse', REPO, dir]);
    git(['sparse-checkout', 'set', SOURCE_DIR], dir);
  } catch (error) {
    fs.rmSync(dir, { recursive: true, force: true });
    throw error;
  }
  return dir;
}

/** Every publishable markdown page, as paths relative to the source root. */
function collectPages(sourceRoot) {
  const pages = [];

  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.name.endsWith('.md')) {
        const relative = path.relative(sourceRoot, full).split(path.sep).join('/');
        if (!EXCLUDE.has(relative)) pages.push(relative);
      }
    }
  };

  walk(sourceRoot);
  return pages;
}

/**
 * The complete desired contents of docs/, as a relative-path -> content map.
 * Building it up front means --check and the real write compare the same thing.
 */
function buildOutput(sourceRoot, pages) {
  const files = new Map();
  const sections = new Set();
  const unknownSections = [];

  for (const page of pages) {
    const raw = readAsLf(path.join(sourceRoot, page));
    files.set(page, transformPage(raw, page));

    const section = page.includes('/') ? page.slice(0, page.indexOf('/')) : null;
    if (section && !sections.has(section)) {
      sections.add(section);
      if (!CATEGORY_LABELS[section]) unknownSections.push(section);
    }
  }

  for (const section of sections) {
    files.set(`${section}/_category_.json`, categoryJson(section));
  }

  if (unknownSections.length > 0) {
    console.warn(
      `\nWarning: no label configured for ${unknownSections.join(', ')} — ` +
        'a name was derived from the folder. Add it to CATEGORY_LABELS in scripts/sync-docs.mjs.',
    );
  }

  return files;
}

function transformPage(raw, page) {
  let content = raw.trimStart();
  for (const [pattern, replacement] of EXTERNAL_LINK_REWRITES) {
    content = content.replace(pattern, replacement);
  }

  // The notice goes *after* the H1, never before it. Docusaurus takes a page's
  // title from the leading H1 and only finds it when nothing precedes it — put
  // the comment first and every page is titled after its filename instead.
  const lines = content.split('\n');
  const h1 = lines.findIndex((line) => line.startsWith('# '));

  if (h1 === -1) {
    console.warn(`  ! ${page} has no H1 — its title will fall back to the filename`);
    return `${GENERATED_NOTICE}\n\n${content}`;
  }

  lines.splice(h1 + 1, 0, '', GENERATED_NOTICE);
  return lines.join('\n');
}

function categoryJson(section) {
  const match = section.match(/^(\d+)[-_.\s]*(.*)$/);
  const position = match ? Number(match[1]) : undefined;
  const label =
    CATEGORY_LABELS[section] ??
    (match ? match[2] : section)
      .split(/[-_\s]+/)
      .filter(Boolean)
      .map((word) => word[0].toUpperCase() + word.slice(1))
      .join(' ');

  return `${JSON.stringify({ label, position }, null, 2)}\n`;
}

/** Replace docs/ wholesale, so a page deleted upstream disappears here too. */
function writeOutput(files) {
  fs.rmSync(DEST, { recursive: true, force: true });

  for (const [relative, content] of [...files].sort(([a], [b]) => a.localeCompare(b))) {
    const target = path.join(DEST, relative);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content, 'utf8');
    console.log(`  ${relative}`);
  }
}

/** Compare what is on disk with what upstream says it should be. */
function reportDrift(files) {
  const onDisk = new Set();
  if (fs.existsSync(DEST)) {
    const walk = (dir) => {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else onDisk.add(path.relative(DEST, full).split(path.sep).join('/'));
      }
    };
    walk(DEST);
  }

  const added = [...files.keys()].filter((f) => !onDisk.has(f));
  const removed = [...onDisk].filter((f) => !files.has(f));
  const changed = [...files.entries()]
    .filter(([f, content]) => onDisk.has(f) && readAsLf(path.join(DEST, f)) !== content)
    .map(([f]) => f);

  if (added.length === 0 && removed.length === 0 && changed.length === 0) {
    console.log('\ndocs/ is up to date.');
    return;
  }

  for (const f of added) console.log(`  + ${f}`);
  for (const f of removed) console.log(`  - ${f}`);
  for (const f of changed) console.log(`  ~ ${f}`);
  console.log(`\ndocs/ is stale: ${added.length} added, ${removed.length} removed, ${changed.length} changed.`);
  process.exitCode = 1;
}

/**
 * Read a file with line endings forced to LF.
 *
 * The temporary clone goes through the same git config as everything else, so
 * on a machine with autocrlf the upstream markdown arrives as CRLF while CI
 * reads it as LF. Left alone, the two write byte-different copies of identical
 * content and each sync rewrites every file. .gitattributes pins the repository
 * side; this pins the script so it does not depend on git config at all.
 */
function readAsLf(file) {
  return fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
}

function git(args, cwd) {
  return execFileSync('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'], encoding: 'utf8' });
}

function fail(message) {
  console.error(`\nsync-docs: ${message}`);
  process.exit(1);
}

main();
