#!/usr/bin/env node
/**
 * Generate the Russian site from the English source.
 *
 * Everything under i18n/ru/ is output, not source. The English text in learn/,
 * src/pages/ and docusaurus.config.ts is the only place either language is
 * written; this script produces the other one. Editing a file under i18n/ru/ by
 * hand works until the next run and then vanishes — the same rule, and for the
 * same reason, as docs/. See STRATEGY.md.
 *
 *   npm run translate              # only what changed since the last run
 *   npm run translate -- --force   # everything, ignoring the manifest
 *   npm run translate -- --check   # report what is stale, write nothing, exit 1
 *   npm run translate -- --only learn/03_flutter   # a path prefix
 *
 * The engine is the Claude CLI in headless mode, so there is no API key to set
 * up and no second bill: whoever can run `claude` can run this. That also makes
 * it an operator tool rather than a CI step — the output is committed and
 * reviewed like any other generated tree.
 *
 * `--check` is the exception and is what CI runs: it compares hashes and needs
 * no CLI, no network and no tokens. It fails the deploy when an English page
 * was edited without re-translating, which otherwise shows up as a Russian URL
 * quietly serving English.
 */

import { execSync, spawn } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fail, ROOT, run } from './env.mjs';

const MODEL = 'claude-opus-5';

/**
 * Bumping this retranslates everything on the next run. The manifest hashes the
 * prompt along with the source, so a change to the instructions below does not
 * quietly apply to new pages only.
 */
const PROMPT_VERSION = 1;

/** How many `claude` processes at once. */
const CONCURRENCY = 4;

/** A single page can take a while; the default 2 minutes is not enough. */
const TIMEOUT_MS = 10 * 60 * 1000;

const LEARN_DIR = path.join(ROOT, 'learn');
const I18N = path.join(ROOT, 'i18n');
const RU = path.join(I18N, 'ru');
const EN = path.join(I18N, 'en');
const LEARN_RU = path.join(RU, 'docusaurus-plugin-content-docs-learn', 'current');
const MANIFEST = path.join(RU, '.translate-manifest.json');

/**
 * Internal to the repository, never published: PAGE_TEMPLATE.md is the authoring
 * guide and carries `draft: true`.
 */
const EXCLUDE = new Set(['PAGE_TEMPLATE.md']);

/**
 * Theme strings — pagination, "Edit this page", the 404. Docusaurus ships its
 * own Russian for all of these and uses it for any key code.json does not
 * override, so translating them again would only create something to keep in
 * sync with a dependency.
 */
const SKIP_KEY_PREFIX = 'theme.';

const GENERATED_NOTICE =
  '<!-- Generated by tools/translate.mjs from the English page. Do not edit: the next run overwrites it. -->';

const MARKDOWN_PROMPT = `You are translating a page of a Flutter competency map from English into Russian for publication on a developer documentation site.

Return the translated Markdown file and nothing else. No preamble, no code fence around the whole file, no commentary.

Rules:

1. Keep the YAML frontmatter block. Translate the values of \`title\`, \`description\` and \`sidebar_label\`. Copy every other key and value byte for byte — \`slug\`, \`sidebar_position\`, \`draft\` and anything else are machine-read and must not change.
2. Keep the Markdown structure exactly: heading levels, tables and their column counts, list markers, bold and italic, blockquotes, horizontal rules, blank lines between blocks.
3. Never alter a URL. Not the path, not the query, not the case.
4. Leave the titles of linked resources in English. They are the names of real books, talks, articles and documentation pages, and a reader who cannot search for the original name cannot find it. Translate the sentence of commentary that follows each link.
5. Leave code, identifiers, file names, package names, CLI commands and the contents of backticks in English.
6. Write the way a good Russian-language engineering blog writes. Established Russian terms where they exist (состояние, тестирование, зависимость, развёртывание); the English term where the Russian one is not what practitioners actually say (Flutter, widget, pull request, code review, CI/CD, backend). Never transliterate a term that has a normal Russian word.
7. Address the reader with "вы" in lower case, and prefer impersonal constructions where the English uses "you" as a generic subject.
8. Translate the meaning, not the word order. English technical prose is heavy with participles and nominalisations that read as machine output in Russian — rewrite those sentences the way a Russian author would have written them in the first place.

The page follows:

`;

const JSON_PROMPT = `You are translating interface strings for a Flutter framework's website from English into Russian.

The input is a JSON object mapping a key to an object with \`message\` (the English string) and, usually, \`description\` (where the string appears — context for you, not something to translate).

Return a JSON object mapping every input key to its Russian translation as a plain string. Return only the JSON, with no code fence and no commentary. Every key in the input must appear in the output.

Rules:

1. This is landing-page and navigation copy, not documentation. It has to be short and it has to sound like it was written in Russian, not translated into it. Match the register: confident and plain, never markety.
2. Respect the length. A button label that doubles in length breaks the layout it sits in.
3. Product and technology names stay as they are: DartWay, Flutter, Serverpod, Dart, GitHub, Telegram, iOS, Android, Web, LMS, CRUD, API, DAU.
4. Keep any punctuation that carries meaning, such as the leading ">" in "> 5000 Users".
5. Where the English uses title case for a heading, use ordinary Russian sentence case.

The strings follow:

`;

async function main() {
  const args = process.argv.slice(2);
  const force = args.includes('--force');
  const check = args.includes('--check');
  const onlyAt = args.indexOf('--only');
  const only = onlyAt === -1 ? null : args[onlyAt + 1];

  if (onlyAt !== -1 && !only) fail('--only needs a path prefix');

  const english = extractEnglishStrings();
  const manifest = force ? {} : readManifest();

  const jobs = [...markdownJobs(english), ...jsonJobs(english)].filter(
    (job) => !only || job.id.startsWith(only),
  );

  const stale = jobs.filter((job) => manifest[job.id] !== job.hash || !fs.existsSync(job.target));

  if (stale.length === 0) {
    console.log(`i18n/ru is up to date — ${jobs.length} sources, nothing to translate.`);
    return;
  }

  if (check) {
    for (const job of stale) console.log(`  ~ ${job.id}`);
    console.log(`\ni18n/ru is stale: ${stale.length} of ${jobs.length} sources need retranslating.`);
    console.log('Run `npm run translate`.');
    process.exitCode = 1;
    return;
  }

  // Checked here rather than at the top of the run: --check is the mode CI uses
  // to catch an English edit that was never translated, and CI has no reason to
  // install the CLI to answer a question about file hashes.
  requireClaude();

  console.log(`Translating ${stale.length} of ${jobs.length} sources with ${MODEL}\n`);

  const nextManifest = { ...manifest };
  let done = 0;
  let failed = 0;

  await pool(stale, CONCURRENCY, async (job) => {
    try {
      const output = await job.translate();
      fs.mkdirSync(path.dirname(job.target), { recursive: true });
      fs.writeFileSync(job.target, output, 'utf8');
      nextManifest[job.id] = job.hash;
      console.log(`  [${++done + failed}/${stale.length}] ${job.id}`);
    } catch (error) {
      failed += 1;
      console.error(`  [${done + failed}/${stale.length}] ${job.id} FAILED: ${error.message}`);
    } finally {
      // Written as each job lands, not at the end: a run interrupted after
      // forty pages should not throw away the forty.
      writeManifest(nextManifest);
    }
  });

  pruneOrphans(jobs, nextManifest);
  writeManifest(nextManifest);

  console.log(`\n${done} translated, ${failed} failed.`);
  if (failed > 0) {
    console.log('Re-run to retry only the ones that failed — the manifest kept the rest.');
    process.exitCode = 1;
  } else {
    console.log('Run `npm run build` before pushing — onBrokenLinks is set to throw.');
  }
}

/* ---------------------------------------------------------------- sources */

/**
 * The English interface strings, as Docusaurus itself extracts them.
 *
 * `write-translations` is the only thing that knows every `translate()` call in
 * src/ and every label in the navbar and footer config, so it is what produces
 * the baseline rather than a parser of our own.
 *
 * The i18n/en tree it writes is deleted immediately afterwards, and git-ignored
 * so a stray one cannot survive. If it were left in place Docusaurus would use
 * it to render the *English* site, and an edit to a string in src/ would show
 * the old text until someone remembered to re-extract — a stale-translation bug
 * in the language that has no translation.
 */
function extractEnglishStrings() {
  fs.rmSync(EN, { recursive: true, force: true });
  execSync('npx docusaurus write-translations --locale en', {
    cwd: ROOT,
    stdio: ['ignore', 'ignore', 'inherit'],
  });

  const read = (relative) => {
    const file = path.join(EN, relative);
    return fs.existsSync(file) ? JSON.parse(readAsLf(file)) : {};
  };

  const strings = {
    'code.json': read('code.json'),
    'docusaurus-theme-classic/navbar.json': read('docusaurus-theme-classic/navbar.json'),
    'docusaurus-theme-classic/footer.json': read('docusaurus-theme-classic/footer.json'),
    'docusaurus-plugin-content-docs-learn/current.json': read(
      'docusaurus-plugin-content-docs-learn/current.json',
    ),
  };

  fs.rmSync(EN, { recursive: true, force: true });
  return strings;
}

/** One job per page under learn/. */
function* markdownJobs() {
  for (const relative of collectMarkdown(LEARN_DIR)) {
    const source = path.join(LEARN_DIR, relative);
    const content = readAsLf(source);

    yield {
      id: `learn/${relative}`,
      target: path.join(LEARN_RU, relative),
      hash: hash(content),
      translate: async () => {
        const translated = await claude(MARKDOWN_PROMPT + content);
        verifyUrls(content, translated);
        return addNotice(translated);
      },
    };
  }
}

/**
 * One job per translation file. The whole file goes in a single request: these
 * strings share a voice, and translating them one at a time produces a page
 * that reads as if four people wrote it.
 */
function* jsonJobs(english) {
  for (const [relative, entries] of Object.entries(english)) {
    const translatable = Object.fromEntries(
      Object.entries(entries).filter(([key]) => !key.startsWith(SKIP_KEY_PREFIX)),
    );

    if (Object.keys(translatable).length === 0) continue;

    const payload = JSON.stringify(translatable, null, 2);

    yield {
      id: `i18n/${relative}`,
      target: path.join(RU, relative),
      hash: hash(payload),
      translate: async () => {
        const translated = parseJson(await claude(JSON_PROMPT + payload), relative);

        const missing = Object.keys(translatable).filter((key) => !(key in translated));
        if (missing.length > 0) {
          throw new Error(`translation dropped ${missing.length} key(s): ${missing.join(', ')}`);
        }

        // Rebuilt in the shape Docusaurus reads, keeping the English text as the
        // description so a reviewer can see both without opening two files.
        const out = {};
        for (const [key, value] of Object.entries(translatable)) {
          out[key] = { message: translated[key], description: value.message };
        }
        return `${JSON.stringify(out, null, 2)}\n`;
      },
    };
  }
}

function collectMarkdown(dir, prefix = '') {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      files.push(...collectMarkdown(path.join(dir, entry.name), relative));
    } else if (entry.name.endsWith('.md') && !EXCLUDE.has(relative)) {
      files.push(relative);
    }
  }
  return files;
}

/* ---------------------------------------------------------------- engine */

/**
 * The prompt goes in over stdin rather than as an argument: pages run to several
 * kilobytes and Windows caps a command line at about thirty-two.
 */
function claude(prompt) {
  return new Promise((resolve, reject) => {
    const child = spawn(...shellCommand(['claude', '-p', '--model', MODEL]));

    let stdout = '';
    let stderr = '';
    const timer = setTimeout(() => {
      child.kill();
      reject(new Error(`no answer in ${TIMEOUT_MS / 1000}s`));
    }, TIMEOUT_MS);

    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', (chunk) => (stdout += chunk));
    child.stderr.on('data', (chunk) => (stderr += chunk));

    child.on('error', (error) => {
      clearTimeout(timer);
      reject(error);
    });

    child.on('close', (code) => {
      clearTimeout(timer);
      if (code !== 0) {
        reject(new Error(`claude exited ${code}: ${stderr.trim().split('\n').pop() ?? ''}`));
        return;
      }
      const output = stdout.replace(/\r\n/g, '\n').trim();
      if (output === '') {
        reject(new Error('the model returned nothing'));
        return;
      }
      resolve(output);
    });

    child.stdin.end(prompt, 'utf8');
  });
}

/**
 * Both external commands are run through a shell on Windows, where `claude` and
 * `npx` are .cmd shims that cannot be executed directly. Node deprecated passing
 * an argument array alongside `shell: true` — the arguments are concatenated,
 * not escaped — so the command is assembled here instead. Everything in it is a
 * constant of this file; nothing user-supplied is ever appended.
 */
function shellCommand(argv) {
  const options = { cwd: ROOT };
  return process.platform === 'win32'
    ? [argv.join(' '), { ...options, shell: true }]
    : [argv[0], argv.slice(1), options];
}

function requireClaude() {
  try {
    execSync('claude --version', { cwd: ROOT, stdio: 'ignore' });
  } catch {
    fail('the `claude` CLI is not on PATH. It is the translation engine — see the header of tools/translate.mjs.');
  }
}

/**
 * Models like to wrap JSON in a fence however firmly they are asked not to, and
 * one stray fence should not cost a whole file's translation.
 */
function parseJson(output, label) {
  const fenced = output.match(/^```(?:json)?\n([\s\S]*?)\n```$/);
  try {
    return JSON.parse(fenced ? fenced[1] : output);
  } catch (error) {
    throw new Error(`${label}: the model did not return valid JSON (${error.message})`);
  }
}

/**
 * Refuse a translation that changed a link.
 *
 * The prompt tells the model to leave URLs alone, but "the prompt said so" is
 * not a guarantee, and the Resources sections are the whole point of these
 * pages: `npm run check-links` verified all 209 of them against the English
 * source, and that verification only carries over to the Russian copy if the
 * copy has the same links. A dropped or invented URL fails the page here rather
 * than being noticed months later by a reader.
 */
function verifyUrls(source, translated) {
  const urls = (text) => (text.match(/https?:\/\/[^\s)<>"'\]]+/g) ?? []).sort();

  const before = urls(source);
  const after = urls(translated);

  const missing = before.filter((url) => !after.includes(url));
  const invented = after.filter((url) => !before.includes(url));

  if (missing.length > 0 || invented.length > 0) {
    const parts = [];
    if (missing.length > 0) parts.push(`dropped ${missing.join(', ')}`);
    if (invented.length > 0) parts.push(`invented ${invented.join(', ')}`);
    throw new Error(`the translation changed links: ${parts.join('; ')}`);
  }
}

/** The notice goes after the H1 — before it, Docusaurus titles the page after its filename. */
function addNotice(content) {
  const lines = content.split('\n');
  const h1 = lines.findIndex((line) => line.startsWith('# '));
  if (h1 === -1) return `${GENERATED_NOTICE}\n\n${content}\n`;
  lines.splice(h1 + 1, 0, '', GENERATED_NOTICE);
  return `${lines.join('\n')}\n`;
}

async function pool(items, size, worker) {
  const queue = [...items];
  const runners = Array.from({ length: Math.min(size, queue.length) }, async () => {
    while (queue.length > 0) await worker(queue.shift());
  });
  await Promise.all(runners);
}

/* -------------------------------------------------------------- manifest */

function readManifest() {
  if (!fs.existsSync(MANIFEST)) return {};
  try {
    return JSON.parse(readAsLf(MANIFEST));
  } catch {
    console.warn('The manifest is unreadable — treating everything as stale.');
    return {};
  }
}

function writeManifest(manifest) {
  fs.mkdirSync(RU, { recursive: true });
  const sorted = Object.fromEntries(Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)));
  fs.writeFileSync(MANIFEST, `${JSON.stringify(sorted, null, 2)}\n`, 'utf8');
}

/** A page renamed or deleted in English leaves a Russian orphan that would still be served. */
function pruneOrphans(jobs, manifest) {
  const live = new Set(jobs.map((job) => job.id));

  for (const id of Object.keys(manifest)) {
    if (live.has(id)) continue;
    delete manifest[id];
  }

  if (!fs.existsSync(LEARN_RU)) return;

  const expected = new Set(jobs.filter((job) => job.target.startsWith(LEARN_RU)).map((job) => job.target));
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
        if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
      } else if (!expected.has(full)) {
        fs.rmSync(full);
        console.log(`  - ${path.relative(ROOT, full).split(path.sep).join('/')} (no English source)`);
      }
    }
  };
  walk(LEARN_RU);
}

/* ----------------------------------------------------------------- utils */

function hash(content) {
  return crypto.createHash('sha256').update(`${PROMPT_VERSION}\n${content}`).digest('hex').slice(0, 16);
}

/** See the same helper in scripts/sync-docs.mjs for why line endings are forced. */
function readAsLf(file) {
  return fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
}

run(main);
